### ISSUE TITLE
How to download data folder

### ISSUE THREAD

**Issue by biortus** [AlexanderKroll/ESP_prediction_function#1]
I use data folder from https://github.com/AlexanderKroll/ESP. However, i met an error like this, FileNotFoundError: [Errno 2] No such file or directory: '../data/additional_data/all_substrates.pkl'

**Comment by AlexanderKroll** [comment]
Dear biortus, 
I am sorry, I made a mistake displaying the link to the data folder on the Readme page of this repository. I fixed it. You can donwload the correct data folder from here: https://doi.org/10.5281/zenodo.7981153
