### ISSUE TITLE
Error extracting data.zip

### ISSUE THREAD

**Issue by zas97** [AlexanderKroll/ESP_prediction_function#2]
I am trying to extract the data.zip archive to run the model and it says that the zip is damaged. I tried downloading it multiple times and I always get the same error. Am I the only one with this error?

**Comment by AlexanderKroll** [comment]
I uploaded a new data.zip file that I created using a different pogram. Could you try to download the file again and see if it is working now? Here is the new download link: https://doi.org/10.5281/zenodo.8046233

**Comment by zas97** [comment]
It's working now, thank you =)
