### ISSUE TITLE
keyerror:args

### ISSUE THREAD

**Issue by palvinaveen** [AlexanderKroll/ESP_prediction_function#4]
When i tried to run your tutorial_ESP prediction.ipynb file  i am encountering key error :args issue in your example code in 88 line which is pasted as below: 

      7           ]
----> 8 df = ESP_predicton(substrate_list = substrates,
      9                enzyme_list = enzymes)
     10 df

File ~/ESP_prediction_function/code/ES_prediction.py:22, in ESP_predicton(substrate_list, enzyme_list)
     20 print("Step 2/3: Calculating numerical representations for all enzymes.")
     21 enzyme_list = ["" if pd.isnull(value) else value for value in enzyme_list]
---> 22 df_enzyme = calcualte_esm1b_ts_vectors(enzyme_list = enzyme_list)
     24 print("Step 3/3: Making predictions for ESP.")
     25 #Merging the Metabolite and the enzyme DataFrame:

File ~/ESP_prediction_function/code/enzyme_representations.py:53, in calcualte_esm1b_ts_vectors(enzyme_list)
     50 regression_location = model_location[:-3] + "-contact-regression.pt"
     52 regression_data = torch.load(regression_location, map_location='cpu')
---> 53 model, alphabet = esm.pretrained.load_model_and_alphabet_core(model_data, regression_data)
     54 #model, alphabet = esm.pretrained.load_model_and_alphabet_local(model_location = model_location)
     57 batch_converter = alphabet.get_batch_converter()

File ~/anaconda3/lib/python3.11/site-packages/esm/pretrained.py:193, in load_model_and_alphabet_core(model_name, model_data, regression_data)
    191     model, alphabet, model_state = _load_model_and_alphabet_core_v2(model_data)
    192 else:
--> 193     model, alphabet, model_state = _load_model_and_alphabet_core_v1(model_data)
    195 expected_keys = set(model.state_dict().keys())
    196 found_keys = set(model_state.keys())

File ~/anaconda3/lib/python3.11/site-packages/esm/pretrained.py:88, in _load_model_and_alphabet_core_v1(model_data)
     85 def _load_model_and_alphabet_core_v1(model_data):
     86     import esm  # since esm.inverse_folding is imported below, you actually have to re-import esm here
---> 88     alphabet = esm.Alphabet.from_architecture(model_data["args"].arch)
     90     if model_data["args"].arch == "roberta_large":
     91         # upgrade state dict
     92         pra = lambda s: "".join(s.split("encoder_")[1:] if "encoder" in s else s)

KeyError: 'args'
 
 I went through your pretrained.py file but there is no specification of  key 'args' . please help me to  resolve the above keyerror 
 Thankyou.

**Comment by AlexanderKroll** [comment]
Hi palvinaveen,

there seems to be a problem with loading the esm model. Did you check the version of the esm-fair package? As specified on the Readme page the version should be 0.4.0.
