### ISSUE TITLE
all_substrate.pkl

### ISSUE THREAD

**Issue by AachenOcean** [AlexanderKroll/ESP_prediction_function#5]
Thanks for your excellent work on ESP. I am wondering where can i find the all_substrate.pkl? Thanks. Is the one called model_ESM_binary_A100_epoch_1_new_split.pkl ？

**Comment by AlexanderKroll** [comment]
When you downloaded the data.zip file from zenodo as specfified on the Readme page, after unzipping you should find the all_substrates.pkl file in the folder "data\additional_data".
