### ISSUE TITLE
problem when running ESP.py

### ISSUE THREAD

**Issue by boqingding** [AlexanderKroll/ESP_prediction_function#7]
ValueError                                Traceback (most recent call last)
Cell In[7], line 5
      1 substrates = ["C1=CC(=C(C=C1O)Cl)Cl",
      2               ]
      3 enzymes = ["MEESKTPHVAIIPSPGMGHLIPLVEFAKRLVHLHGLTVTFVIAGEGPPSKAQRTVLDSLPSSISSVFLPPVDLTDLSSSTRIESRISLTVTRSNPELRKVFDSFVEGGRLPTALVVDLFGTDAFDVAVEFHVPPYIFYPTTANVLELTEPLMLPGCVPVAGKDFLDPAQDRKDDAYKWLLHNTKRYKEAEGILVNTFFELEPNAIKALQEPGLDKPPVYPVGPLVNIGKQEAKQTEESECLKWLDNQPLGSVLYVSFGSGGTLTCEQLNELALGLADSEQRFLWVIRSPSGIANSSYFDSHSQTDPLTFLPPGFLERTKKRGFVIPFWAPQAQVLAHPSTGGFLTHCGWNSTLESVVSGIPLIAWPLYAEQKMNAVLLSEDIRAALRPRAGDDGLVRREEVARVVKGLMEGEEGKGVRNKMKELKEAACRVLKDDGTSTKALSLVALKWKAHKKELEQNGNH",
      4            ]
----> 5 df = ESP_predicton(substrate_list = substrates,
      6                enzyme_list = enzymes)
      7 df

File ~\dataframe\ES_prediction.py:27, in ESP_predicton(substrate_list, enzyme_list)
     25 #Merging the Metabolite and the enzyme DataFrame:
     26 df_ES = pd.DataFrame(data = {"substrate" : substrate_list, "enzyme" : enzyme_list, "index" : list(range(len(substrate_list)))})
---> 27 df_ES = merging_metabolite_and_enzyme_df(df_met, df_enzyme, df_ES)
     28 df_ES_valid, df_ES_invalid = df_ES.loc[df_ES["complete"]], df_ES.loc[~df_ES["complete"]]
     29 df_ES_valid.reset_index(inplace = True, drop = True)

File ~\dataframe\ES_prediction.py:58, in merging_metabolite_and_enzyme_df(df_met, df_enzyme, df_ES)
     55 except:
     56 	gnn_rep, esm1b_rep = "", ""
---> 58 if gnn_rep == "" or esm1b_rep == "" or df_ES["enzyme"][ind] == "":
     59 	df_ES["complete"][ind] = False
     60 else:

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

**Comment by AlexanderKroll** [comment]
Hi boqingding,

sorry for my late response. Thanks for pointing this out. It seems to depend on the Python version whether the code works. I adjusted it such that it now hopefully works for most versions.

**Comment by guoliang-biomap** [comment]
Dear AlexanderKroll:
    Similar mistake still persists:
File ~/ESP_prediction_function/code/ES_prediction.py, line 27, in ESP_predicton
    df_ES = merging_metabolite_and_enzyme_df(df_met, df_enzyme, df_ES)
  File ~/ESP_prediction_function/code/ES_prediction.py, line 63, in merging_metabolite_and_enzyme_df
    if gnn_rep != "":
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()
